### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yamalight** [jescalan/indx#2]
Hi there! Which license is used for this project? Can you please specify it in package.json?

**Comment by jescalan** [comment]
Hi Tim,

Sorry about that, this is an old project which doesn't updated frequently, as it's small and stable. I totally dropped the ball on licensing initially. Just added a license file, and a note to the readme as well as a `license` to `package.json` and published all of this as `0.2.3`. Thanks for the heads up!

**Comment by yamalight** [comment]
awesome, thanks!
